language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-nvidia.gemspec
- gem install sensu-plugins-nvidia-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: My2XCFrEXTwD95gajcCgdwu0mWioDISKRBH2AG773jxQGZnsK9ABHOuIfGlyb3dgxFSCTQvFmeEnlgXrfiThyRF8Pn49aKl7BTqfSxutgabgleAt/CEj5zbfP08IQxueRnQaGx/1YwvGOc9qTyAADwewEr2Rd9aKRRmdM8pDbKg=
  gem: sensu-plugins-nvidia
  on:
    tags: true
    repo: sensu-plugins/sensu-plugins-nvidia
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1

